(ns hive-addon.runtime.plan
  "Pure planning for client runtimes: which directory a runtime installs into,
   the loader a client runs, and the effect plans that install it, remove it,
   and activate it in clients that are already running.

   Every function here is pure. Paths are computed from an explicit :home, so
   nothing reads the environment; hive-addon.runtime.boundary runs the plans.

   A client kind is data (a profile in `default-profiles` or one a host passes)
   plus a loader kind. Rendering is open for extension through the
   `loader-source` and `live-commands` multimethods, dispatched on the
   profile's :profile/loader, so a new client adds methods rather than branches.

   Rationale lives in hive memory (KG-linked), not here."
  (:require [clojure.string :as str]
            [hive-addon.runtime.schema :as rs]
            [malli.core :as m]))

;; Copyright (C) 2026 Pedro Gomes Branquinho (BuddhiLW) <pedrogbranquinho@gmail.com>
;;
;; SPDX-License-Identifier: MIT

;; =============================================================================
;; Profiles
;; =============================================================================

(def default-profiles
  "Client kind -> profile. Vim and Neovim both autoload every runtime directory
   under pack/*/start at startup, and both run the same Vim script loader."
  {:vim  {:profile/client :vim
          :profile/install-root "~/.vim/pack/hive/start"
          :profile/loader-path "plugin/zz_hive_runtime.vim"
          :profile/loader :vimscript}
   :nvim {:profile/client :nvim
          :profile/install-root "~/.local/share/nvim/site/pack/hive/start"
          :profile/loader-path "plugin/zz_hive_runtime.vim"
          :profile/loader :vimscript}})

(defn expand-home
  "PATH with a leading ~/ replaced by HOME."
  [path home]
  (if (str/starts-with? path "~/")
    (str (str/replace home #"/+$" "") (subs path 1))
    path))

(defn install-dir
  "The directory runtime ID installs into for PROFILE."
  [profile id home]
  (str (str/replace (expand-home (:profile/install-root profile) home) #"/+$" "")
       "/" id))

;; =============================================================================
;; Bindings
;; =============================================================================

(def ^:private placeholder-re #"\{\{([a-z][a-z0-9-]*)\}\}")

(defn placeholders
  "The binding names S refers to, as keywords."
  [s]
  (into #{} (map (comp keyword second)) (re-seq placeholder-re s)))

(defn unbound
  "Binding names DECL's on-load commands use that VALUES does not supply,
   sorted."
  [decl values]
  (->> (:runtime/on-load decl)
       (mapcat placeholders)
       (remove #(contains? values %))
       (into (sorted-set))
       vec))

(defn substitute
  "S with every {{name}} replaced by (get VALUES :name). Unknown names are left
   as written; `unbound` reports them before a plan is built."
  [s values]
  (str/replace s placeholder-re
               (fn [[whole k]] (str (get values (keyword k) whole)))))

(defn on-load-commands
  "DECL's on-load commands with VALUES substituted."
  [decl values]
  (mapv #(substitute % values) (:runtime/on-load decl [])))

;; =============================================================================
;; Loader rendering (open by loader kind)
;; =============================================================================

(defmulti loader-source
  "Source of the loader file that runs COMMANDS once PROFILE's client has
   loaded runtime ID."
  (fn [profile _id _commands] (:profile/loader profile)))

(defmulti live-commands
  "Commands that make an already-running client load the runtime installed at
   DIR (which then runs its own loader). A running client may hold an older
   version of the same runtime: its autoload scripts are sourced as well when
   the client can replace them, and the client is told to restart when it
   cannot (a Vim that loaded them from another directory)."
  (fn [profile _dir] (:profile/loader profile)))

(defn vim-string
  "S as a single-quoted Vim string literal."
  [s]
  (str "'" (str/replace s "'" "''") "'"))

(defn- vim-ident
  [id]
  (str/replace id #"[^A-Za-z0-9]" "_"))

(defmethod loader-source :vimscript
  [_profile id commands]
  (let [ident (vim-ident id)
        guard (str "g:loaded_hive_runtime_" ident)]
    (str/join
     "\n"
     (concat
      [(str "\" Generated by hive-addon for runtime " id ". Removed when the addon shuts down.")
       (str "if exists(" (vim-string guard) ")")
       "  finish"
       "endif"
       (str "let " guard " = 1")
       ""
       "function! s:activate() abort"]
      (map #(str "  " %) commands)
      ["endfunction"
       ""
       "if v:vim_did_enter"
       "  call s:activate()"
       "else"
       (str "  augroup hive_runtime_" ident)
       "    autocmd!"
       "    autocmd VimEnter * ++once call s:activate()"
       "  augroup END"
       "endif"
       ""]))))

(defmethod live-commands :vimscript
  [_profile dir]
  (let [d (vim-string dir)
        autoload (vim-string (str dir "/autoload/**/*.vim"))
        plugin (vim-string (str dir "/plugin/**/*.vim"))]
    [(str "execute 'set runtimepath+=' . fnameescape(" d ")")
     ;; Autoload scripts of this runtime that the running Vim already loaded
     ;; from ANOTHER directory. Vim keeps the first definition of an autoload
     ;; function and refuses the second (E1073), so re-sourcing would leave the
     ;; old script in place while its siblings load new and call it with new
     ;; signatures (E118). Measured 2026-09-13 on hive-vessel's wire.vim/ops.vim.
     (str "let g:hive_runtime_stale = exists('*getscriptinfo')"
          " ? filter(map(getscriptinfo(), 'v:val.name'),"
          " {_, n -> strpart(n, 0, len(" d ")) !=# " d
          " && !empty(filter(map(glob(" autoload ", 0, 1), {_, f -> strpart(f, len(" d "))}),"
          " {_, t -> strpart(n, len(n) - len(t)) ==# t}))})"
          " : []")
     (str "if empty(g:hive_runtime_stale)"
          " | call map(sort(glob(" autoload ", 0, 1)) + sort(glob(" plugin ", 0, 1)),"
          " {_, f -> execute('source ' . fnameescape(f))})"
          " | else | echohl WarningMsg"
          " | echomsg 'hive runtime: ' . g:hive_runtime_stale[0]"
          " . ' is already loaded from another directory; restart Vim to use ' . " d
          " | echohl None | endif")]))

;; =============================================================================
;; Plans
;; =============================================================================

(defn install-plan
  "Effects that install DECL for PROFILE from SOURCE-DIR, with the loader
   rendered from VALUES. Replaces any previous install of the same runtime.

   Returns {:dir d :plan [Effect ...]}, or {:error message} when an on-load
   command names a binding VALUES lacks."
  [profile decl {:keys [home source-dir values]}]
  (let [missing (unbound decl values)]
    (if (seq missing)
      {:error (str "runtime " (:runtime/id decl) " has unbound placeholders: "
                   (str/join ", " (map name missing)))}
      (let [dir (install-dir profile (:runtime/id decl) home)]
        {:dir dir
         :plan [{:effect :fs/delete-tree :path dir}
                {:effect :fs/copy-tree :from source-dir :to dir}
                {:effect :fs/write
                 :path (str dir "/" (:profile/loader-path profile))
                 :content (loader-source profile (:runtime/id decl)
                                         (on-load-commands decl values))}]}))))

(defn uninstall-plan
  "Effects that remove DECL's install for PROFILE."
  [profile decl home]
  [{:effect :fs/delete-tree :path (install-dir profile (:runtime/id decl) home)}])

(defn live-plan
  "Effects that activate the runtime installed at DIR in running clients."
  [profile dir]
  [{:effect :client/eval
    :client (:profile/client profile)
    :commands (live-commands profile dir)}])

(m/=> expand-home [:=> [:cat :string :string] :string])
(m/=> install-dir [:=> [:cat rs/ClientProfile rs/RuntimeId :string] :string])
(m/=> substitute [:=> [:cat :string [:map-of :keyword :any]] :string])
(m/=> uninstall-plan [:=> [:cat rs/ClientProfile rs/RuntimeDecl :string] rs/Plan])
